### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by tmikaeld** [BlenderDude/yubico-node#3]
How do i use this library?

I'm stuck at using the Response class and when i try using this:
```
const yu = require('./yubico-node/dist/index');

const yubico = new yu.Yubico({
  clientId: "666", 
  secret: "mySecret", 
  sl: "secure", 
  timeout: 1000
});

const otpString = 'cchcecbjkvdidvghuvuerkrihudhnivndtuugrjnutir';
(async () => {
    try {
        var result = await yubico.verify(otpString);
        console.log(result.ResponseStatus);
    } catch (e) {
      console.log(e);
    }
})();
```

I always get that the OTP has been seen, even though it's the first time it's used.

**Comment by BlenderDude** [comment]
Just loaded in the library and seem to be getting the same error response. I will look into this and get back to you when I find the error. Something in their API might have changed as it was definitely working when I posted this lib.

**Comment by BlenderDude** [comment]
It seems that when the `sl` parameter is set to `secure`, the network tolerances allowed are extremely slim. It worked for me, but when I bumped up my network latency, it did not work. If you use the settings `fast`, it will work as intended. Along with that, in the response, there is no property called `ResponseStatus` as that is an enum type to describe the status. You should use the getter properties that I defined in the README.md in order to access the status. In your case you would want `res.getStatus()`. You should also test with a code that is generated on the spot versus hard coded. Here is the code I used to test

```javascript

const yu = require("yubico-node");
const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question("Tap your OTP key ", async oneTimePassword => {
  const yubico = new yu.Yubico({
    clientId: "[clientId]",
    secret: "[secret]",
    sl: "fast"
  });

  try {
    var res = await yubico.verify(oneTimePassword);
    console.log(res);
  } catch (e) {
    console.log(e);
  }

  rl.close();
});


```

**Comment by tmikaeld** [comment]
@BlenderDude Thanks for the quick answer!

Sorry I forgot that since you're throwing an error there's no res.getStatus() to use.

I didn't expect the network to be a problem when it comes to the sl setting. 

It seems that it only works 3 out of 10 times no matter what sl value that I set.
Those that succeed always has sl 25.

However, if i only set to use a **single** api server, then it succeeds 100% of the time and the sl is still set to 25 or 50 in the responses.

Are you sure the api servers can be used in a race?

**Comment by BlenderDude** [comment]
@tmikaeld as per the Yubico API documentation, you are supposed to send the request out to all the API servers and accept the first one that response. Upon further thinking about it, I think the documentation meant to say the first server that returns a successful response. This makes way more sense. I am going to update the package later today and get a new version out that waits for the first successful response, and only throws if all the servers fail. I will also put in an issue with Yubico to make their documentation clearly state that.

Their documentation states

> Clients should send authentication requests to all of them in parallel, and utilize the first response received for added reliability should one or more of the api servers be offline

**Comment by BlenderDude** [comment]
I have gone through and rewrote the core request code to allow for a race to the first successful response instead of the first response in general. You can read more about it in the PR above. I have tested all SL values and the like and it seems that the proper response is always generated regardless of network latency or server response rate. You should now upgrade to library version `1.0.2` in NPM to allow for the updates. Thanks for catching this bug!

**Comment by tmikaeld** [comment]
@BlenderDude Thank you so much for looking into it so quickly 👍
